### ISSUE TITLE
token list for fuse swap should be taken automatically from fuseswap

### ISSUE THREAD

**Issue by sirpy** [GoodDollar/GoodProtocolUI#122]
- [ ] Take token list directly from uniswap/fuseswap sdk
- [ ] find out if it is possible to take directly from their github repo dynamically (I think in our code some lists are already read dynamically)

**Comment by Devartjoker** [comment]
@sirpy From what I could find, fuseswap and uniswap are themselves using the files that we refer to. If the behaviour we have at the moment is not what we want, please tell me what should be fixed in more detail.
<img width="1038" alt="image" src="https://user-images.githubusercontent.com/97535045/154706292-ec779a84-f7ad-4a5d-9a11-bb543bb9c0cc.png">
<img width="1187" alt="image" src="https://user-images.githubusercontent.com/97535045/154706362-103ac8a5-ae33-4847-8ed9-da10bf1bc2dd.png">
