### ISSUE TITLE
Top nav bar hidden on mobile browsers, bottom bar misbehaving

### ISSUE THREAD

**Issue by patpedrosa** [GoodDollar/GoodProtocolUI#155]
**Bug Description**
The top nav bar is hidden under safari's top nav on some mobile browsers

**Steps to Reproduce**
1. Go to goodswap.xyz using your phone
2. Try to switch to a different tab
3. Fail to find the top nav bar :)

I managed to reproduce this on Safari at first, but it's now working. A user (report in the comments) reproduced this in multiple browsers, including metamask's.

**Expected Behavior**
See the top nav bar

![IMG_4360](https://user-images.githubusercontent.com/49105975/155126989-71c41c88-03e3-4836-8a9c-9b56a398b999.PNG)

**Comment by patpedrosa** [comment]
User report:

![IMG_4368](https://user-images.githubusercontent.com/49105975/155200394-8fe6308d-bbf5-4537-912a-8d0f184e094f.PNG)
![IMG_4369](https://user-images.githubusercontent.com/49105975/155200390-89f54a54-9d06-4a39-bf7f-0f58b8b31c9d.PNG)
![IMG_4370](https://user-images.githubusercontent.com/49105975/155200368-59b931e7-e09b-4bad-bc8e-c5220256da33.PNG)

**Comment by L03TJ3** [comment]
@patpedrosa I added a short-time fix so that at least the navbars work on all mobile browsers

Then only a question remains
Below is illustrated what happens, and what is expected solely based on the code:
![image](https://user-images.githubusercontent.com/6606028/155864088-12d83181-83f7-431f-b1f7-7490cfaf0720.png)

just to clarify this beautiful picasso
what now happens is, the top bar pushes everything down

what the code wanted it to do, was to have the menu above the content, and blur the background.

What is the desired design decision here?

**Comment by sirpy** [comment]
@L03TJ3 always look at sushiswap/uniswap for how things are expected to work in terms of UI

**Comment by L03TJ3** [comment]
I am going to create a general issue for mobile, the navbars are fixed for now
