### ISSUE TITLE
(Bug) Use claim button to connect

### ISSUE THREAD

**Issue by L03TJ3** [GoodDollar/GoodProtocolUI#316]
Claim button requests to connect and then should show either action modal or verify uniqueness modal.

Current bugs: 
 - [x] - 2a. Currently always requests to switch to celo
 - [x] - 3. It does not properly await blockchain data to decide which modal to show

**Comment by johnsmith-gooddollar** [comment]
@patpedrosa @L03TJ3 This doesn't looks like a bug but the feature request.
Need to do it after #318 #319 will be fixed

**Comment by L03TJ3** [comment]
Rejected 2a.
First it was always requesting to connect to celo
Now it stays on the chain if fuse/celo
Else it requests to switch to > celo if network in wallet selected is not supported by gooddapp.


Request is:
When user uses the claim-button to connect, by default it should try and switch to CELO after connecting. Always, no matter the chain

**Comment by sirpy** [comment]
@patpedrosa why do we need to force the user to claim first on Celo? it just complicates things and more actions for the user

**Comment by sirpy** [comment]
@patpedrosa we are but obviously there are communication issues.
What you described doesn't explain the flow that @L03TJ3 described:

Only in the case when user wallet is not connected:
1. user connects wallet
2. we find that wallet is already on Fuse
3. force user to switch to Celo

This doesnt make sense, since if wallet is already on Fuse the quickest route is to Claim on fuse.
Otherwise for users that want to claim on both fuse and celo they will have to switch back again to fuse.

maybe it makes sense if we add step 2a. check if user has claimed already on fuse 3. switch to Celo.
but then we can ask the same question why not switch to Fuse if user already claimed on Celo?

All in all this flow is inconsistent and confusing.

**Comment by L03TJ3** [comment]
@patpedrosa the only downside to your suggested flow is that if someone connected with the idea to claim on fuse (and has selected in its wallet)
That the request to switch will break the flow.
1. user connects (with fuse in wallet selected)
2. user gets request to switch to Celo
3. user cancels
4. user needs to click claim again

Where currently the flow is
1. user connects
2a. If fuse or celo, request to claim
2b. if unsupported chain, request to switch to celo

**Comment by sirpy** [comment]
@patpedrosa we are not targeting these personas for ever, you are asking most new users to claim on both chains.
so initially user will claim on  celo -> switch to fuse -> claim on fuse
next day user comes back he is on fuse now he needs to switch to celo -> claim celo -> switch to fuse -> claim fuse
instead of claim fuse -> switch to celo -> claim celo

This is super annoying when the app asks you to switch chain when you dont want to.

GD Wallet users if they claim in the wallet for fuse, and WC to claim on celo then it is expected that next day their WC is still connected to Celo, if they didnt "disconnect".

**If anything I would would change the GoodWallet behaviour that if the dapp you are connecting to is gooddapp it will be Celo by default and not change gooddap logic which effects also non gd wallet users.**

**Comment by sirpy** [comment]
my proposed solution was
If anything I would would change the GoodWallet behaviour that **if the dapp you are connecting to is gooddapp** it will be Celo by default and not change gooddap logic which effects also non gd wallet users.

**Comment by sirpy** [comment]
@patpedrosa @L03TJ3 @vldkhh 
I've pushed a hotfix to the wallet, so when connecting ONLY TO GOODDAPP it will force Celo as the initial network
when connecting to any other dapp it will use the chain requested from the dapp
