### ISSUE TITLE
create a global "please sign tx in your wallet" modal

### ISSUE THREAD

**Issue by sirpy** [GoodDollar/GoodProtocolUI#417]
- based on usedapp notifications
- when a tx is in the waiting for sig state show a modal
- once a tx is in pending state you can then trigger the toast for txs

**Comment by L03TJ3** [comment]
@decentralauren not sure what to do with this or how to give it a 'priority-level'.
This is about what was discussed for user-feedback on gooddapp (including toasts).
and a more general implementation of transaction modals.

1. this only relates to anything that has been build since celo-launch (claim flow / buy-gd / microbridge)
2. currently we only have the claim-flow live and already has a sign-tx modal in the flow

**Comment by decentralauren** [comment]
@L03TJ3 OK so the only benefit to implementing toasts now is for the claim flow to have a pending confirmation after the transaction is signed? Doesn't seem useful at this time, though adding toasts in the future may be appropriate.

**Comment by decentralauren** [comment]
Closing to create a new ticket for improving dapp <> wallet feedback during sign transactions.
