### ISSUE TITLE
Update text user should see after staking

### ISSUE THREAD

**Issue by sirpy** [GoodDollar/GoodProtocolUI#80]
Currently after staking, user is immediatly shown the dialog "Did you just create UBI for thousands of people around the 
 - [x] Modify dialogue from "Did you just create UBI for thousands of people around the world?" to "Your staking transaction for generating UBI for thousands of people around the world has just been broadcasted to the network"; OR if the tx is confirmed, just by "You did just create UBI for thousands of people around the world!".
 - [x] Modify "Yes I Did" button text to "Go to portfolio".

**Comment by sirpy** [comment]
@sepu85 what do you think about the this dialog and "yes I did" specifically is that clear enough?

**Comment by sepu85** [comment]
@sirpy I find that asking question to the user after they perform any action is confusing.

as a DeFi user, I'd like the UX to give me answers and clarifications about what I´m doing... not making me question.

I'm guessing you guys designed like this to make sure the user confirms by his own transaction instead of making the app giving him such a confirmation.

My suggestion is to change both dialogue and "Yes I Did" button.

- [ ] Modify dialogue from "Did you just create UBI for thousands of people around the world?" to "Your staking transaction for generating UBI for thousands of people around the world has just been broadcasted to the network.
- [ ] Modify "Yes I Did" button text to "Go to portfolio".

**Comment by sirpy** [comment]
I agree. I wasn't involved much in the UX.
What about waiting for the TX to be confirmed? do you think we should have
the user wait? otherwise we need some kind of indication, like in uniswap
at the top right they show that a TX is pending

**Comment by L03TJ3** [comment]
What work has already been done on this?

So to get it clear.
What is needed is:
Update Text + Button
Add pending/confirmation Toast notification

Correct?

**Comment by sirpy** [comment]
@L03TJ3 so the text has been modified a little, but you can review and make suggestions
I think a toast notifications could be a nice addition... does suhsiswap has that component?

**Comment by mukulshakya** [comment]
Hi @sepu85 Please tag me after finalizing the details. Thanks

**Comment by mukulshakya** [comment]
@sepu85 i thought there is some discussion going on on finalizing the message. 

I'll refer to the #80, thank you

**Comment by L03TJ3** [comment]
@mukulshakya I was just trying to determine what had been done yet!
was not necessarily trying to open up a discussion about the message itself.

**Comment by L03TJ3** [comment]
@sirpy I haven't pinned down the specific component yet, but it should be existing in sushiswap-interface somewhere.
It might be just the Alert component. but I am building locally now to make sure

**Comment by L03TJ3** [comment]
If we would build in the pending/confirmed transaction toast notification.
Only for staking for now?
Or should I look into doing it for all transactions (so swapping etc)?

**Comment by L03TJ3** [comment]
@sirpy has it been a choice to not put full transaction details (recent transactions) in redux store? (for now only: time / from / hash)

**Comment by L03TJ3** [comment]
NVM!
I think I see that it just hasn't been fully utilized yet

**Comment by patpedrosa** [comment]
![Screen Shot 2022-01-18 at 13 48 11](https://user-images.githubusercontent.com/49105975/149984941-f67d7289-4901-4545-aeb1-85771151313c.png)

"You need to sign the transaction" is confusing because the signing happens before this modal shows. I've done this twice now - and both times I signed before this screen.


Also, I think we need to switch the copy to an affirmation:
"  **Congratulations!**
You are creating UBI to thousands of people around the world." 

No questioning. A staker IS creating UBI.


On these blue buttons that are shown everywhere, but here represented as GO TO PORTFOLIO, add padding to the left and right sides that is the same size as the top and bottom ones, otherwise the copy looks crammed.

I think we should also remove the "CLOSE" button since we already have a close icon at the top right. It's redundant and the main action we want to complete after this is to check their portfolio, hence the big blue button.

**Comment by L03TJ3** [comment]
![image](https://user-images.githubusercontent.com/6606028/150163583-2753b96b-0886-4b1d-bb51-2683f1003a2e.png)

@sepu85 @patpedrosa you both had a say about the text

which one would you guys prefer?

@patpedrosa funny thing, the padding now is actually the same ;)
but it doesn't seem like it cause of round borders so I did change it
and yes, the bottom text of the signing shouldn't be there anymore after the confirmation

O, and in general.
it's a really small addition to this, but personally, I like with buttons to have some sort of hover effect (slightly darker color of initial) when hovering over them
Idk, feels less... flat? static?
Should I add this for the portfolio button?
as the same blue button appears in more places, so to keep it consistent, it could be globally updated?
or just, no...

**Comment by L03TJ3** [comment]
So, if the discussion is now closed for the wording?
I now went with the first image posted as pending text. The second one as confirmed.

@sepu tho I changed your wording slightlyyyy... if you don't mind... :)
Your staking transaction for generating UBI for thousands... >
Your staking transaction which will generate UBI for thousands... 
(to remove the double for)

also DID add the hover effect for the button, I believe it feels less static like that
if any objection I will remove this before merging later
this will affect all similar buttons (stake / withdraw / airdrop / connect)

**Comment by sepu85** [comment]
all good from my side!! I'm also ok with Pat's suggestion.

**Comment by L03TJ3** [comment]
Current Production Bugs:
![image](https://user-images.githubusercontent.com/6606028/152748525-90f59941-17b9-43e1-9cac-0e16601d18fa.png)

![image](https://user-images.githubusercontent.com/6606028/152748628-efc7a2b2-1bd9-4319-964a-0a235f185423.png)
